### ISSUE TITLE
Allow running this container without --privileged

### ISSUE THREAD

**Issue by lostapathy** [linuxserver/docker-openvpnas#44]
Back on #26 I made a PR that got merged by @sparklyballs, then reverted, that made this image run without requiring it to run in privileged mode, and also made it suitable to run out of docker-compose.  Needing to run privileged and not being able to run easily with docker-compose makes this container not usable in a lot of environments.

Based on the comment given on #26, I feel like this change is desirable but I'm not quite sure what the next steps are.

Are you guys interested in improving this image as I tried to do on #26, or should I go elsewhere?  If so, what are next steps?

thanks!

**Comment by j0nnymoe** [comment]
Curious to know what issues you are using this container with docker-compose? In-theory it's no different and it's the first we've heard that this is an issue?

**Comment by lostapathy** [comment]
I honestly don't remember the issue with docker-compose - it's been a year since I submitted #26.  It may well have been a problem with my environment not liking privileged containers, as well.

Either way - #26 seems like a tiny change to make that enables the container to run unprivileged, so I'm not sure what resistance there would be to merging that?

**Comment by tylerpace** [comment]
FWIW, I use docker-compose and I do not run this container in privileged mode.

```
  openvpn:
    container_name: openvpn
    image: linuxserver/openvpn-as:latest
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TZ=${TZ}
      - INTERFACE=${OPENVPN_INTERFACE}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ovpn-data:/config
    labels:
      - "autoheal=true"
    depends_on:
      - pihole
```

They key portions are `cap_add` and `devices`. Adding those settings gives the container exactly what it needs to run without enabling a full blown `privileged: true` container.
